apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: buildless-serverless
  name: buildless-serverless-function-editor-role
rules:
  - apiGroups:
      - serverless.kyma-project.io
    resources:
      - functions
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - serverless.kyma-project.io
    resources:
      - functions/status
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: buildless-serverless
  name: buildless-serverless-function-viewer-role
rules:
  - apiGroups:
      - serverless.kyma-project.io
    resources:
      - functions
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - serverless.kyma-project.io
    resources:
      - functions/status
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: buildless-serverless-manager-role
rules:
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - apps
    resources:
      - deployments/status
    verbs:
      - get
  - apiGroups:
      - serverless.kyma-project.io
    resources:
      - functions
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - serverless.kyma-project.io
    resources:
      - functions/status
    verbs:
      - get
      - patch
      - update
