apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: buildless-serverless
    control-plane: controller-manager
  name: buildless-serverless-controller-manager
  namespace: kyma-system
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: controller-manager
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        control-plane: controller-manager
    spec:
      containers:
        - args:
            - --metrics-bind-address=:8443
            - --leader-elect
            - --health-probe-bind-address=:8081
          command:
            - /manager
          image: mkejuu/buildless-serverless:29-11-v1
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          name: manager
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
            requests:
              cpu: 10m
              memory: 64Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          env:
            - name: APP_FUNCTION_IMAGENODEJS20
              value: "europe-docker.pkg.dev/kyma-project/prod/function-runtime-nodejs20:main"
            - name: APP_FUNCTION_IMAGE_PYTHON312
              value: "europe-docker.pkg.dev/kyma-project/prod/function-runtime-python312:main"
      securityContext:
        runAsNonRoot: true
      serviceAccountName: buildless-serverless-controller-manager
      terminationGracePeriodSeconds: 10
