apiVersion: serverless.kyma-project.io/v1alpha2
kind: Function
metadata:
  labels:
    app.kubernetes.io/name: buildless-serverless
    app.kubernetes.io/managed-by: kustomize
  name: function-sample
spec:
  foo: bar
  # TODO(user): Add fields here
