name: push

on:
  push:
    branches: [ "main", "release-*" ]

jobs:
  builds:
    uses: ./.github/workflows/_build-push-release.yaml
  
  integrations:
    needs: builds
    uses: ./.github/workflows/_integration-tests-push.yaml
  
  upgrades:
    needs: builds
    uses: ./.github/workflows/_upgrade-tests.yaml
